const route = {
    home:'/',
    productDetail:'/product-detail/:slug',
    cart:'/cart',
    login:'/login',
    register:'/register',
    resetPassWord:'/reset-password',
    about:'/about-us',
    contact:'/contact',
    wishlist:'/wishlist',
    categories: '/categories',
    checkout: '/checkout',
    profile: '/profile',
    order: '/order',
    paymentVNPay:'/payment/result',
    orderTracking: '/order-tracking',
    searchCatalog:'/catalogsearch/result',
    // Admin
    dashBoard:'/admin/dashboard',
    productManager:'/admin/product',
    categoryManager:'/admin/category',
    userManager:'/admin/user',
    orderManager:'/admin/order',
    reviewManager:'/admin/review',
    brandManager:'/admin/brand',
    imageManager:'/admin/images',
}
export default route;